package tools

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/sirupsen/logrus"

	"golang.org/x/crypto/ssh"
)

type SSHConfig struct {
	Port             int
	User             string
	IdentityFilePath string
}

const sshConfigTemplate = `# AUTO-GENERATED BY VOYAGER. DO NOT EDIT.
Host localhost
  StrictHostKeyChecking no
  HostName localhost
  Port {{.Port}}
  User {{.User}}
  IdentityFile {{.IdentityFilePath}}
`

func writeVoyagerSSHConfig(voyagerConfigPath string, config *SSHConfig) (string, error) {
	sshDirPath := filepath.Join(voyagerConfigPath, "ssh")
	if err := os.MkdirAll(sshDirPath, 0700); err != nil {
		return "", fmt.Errorf("failed to create SSH directory: %v", err)
	}

	voyagerSshConfigPath := filepath.Join(sshDirPath, "config")
	file, err := os.OpenFile(voyagerSshConfigPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return "", fmt.Errorf("failed to open SSH config file: %v", err)
	}
	defer file.Close()

	tmpl, err := template.New("ssh_config").Parse(sshConfigTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse SSH config template: %v", err)
	}
	err = tmpl.Execute(file, config)
	if err != nil {
		return "", fmt.Errorf("failed to write SSH config: %v", err)
	}
	println(voyagerSshConfigPath)
	return voyagerSshConfigPath, nil
}

func EnsureVoyagerSshConfig(sshConfigPath, voyagerConfigPath string, config *SSHConfig) error {
	voyagerSshConfigPath, err := writeVoyagerSSHConfig(voyagerConfigPath, config)
	if err != nil {
		return err
	}
	desiredString := fmt.Sprintf("Include %s", voyagerSshConfigPath)
	content, err := os.ReadFile(sshConfigPath)
	if err != nil {
		if os.IsNotExist(err) {
			err = os.WriteFile(sshConfigPath, []byte(desiredString+"\n\n"), 0644)
			if err != nil {
				return fmt.Errorf("failed to create ssh config file: %v", err)
			}
			return nil
		}
		return fmt.Errorf("failed to read ssh config file: %v", err)
	}

	lines := strings.Split(string(content), "\n")

	// Check if the first line matches the desired string
	if len(lines) > 0 && lines[0] == desiredString {
		return nil
	}

	// If the desired string doesn't exist at the top, add it
	lines = append([]string{desiredString}, lines...)

	// Join the lines back into a single string
	newConfigContent := strings.Join(lines, "\n")

	// Write the updated content back to the file
	err = os.WriteFile(sshConfigPath, []byte(newConfigContent), 0644)
	if err != nil {
		return fmt.Errorf("failed to update ssh config file: %v", err)
	}
	return nil
}

func EnsureSSHKeyPair(directory string) (publicKeyPath string, privateKeyPath string, err error) {
	// Check if the directory exists, create it if necessary
	err = os.MkdirAll(directory, 0700)
	if err != nil {
		return "", "", fmt.Errorf("failed to create directory: %v", err)
	}

	// Set the file paths for the private and public keys
	privateKeyPath = filepath.Join(directory, "id_rsa")
	publicKeyPath = filepath.Join(directory, "id_rsa.pub")

	// Check if the private key already exists
	if _, err = os.Stat(privateKeyPath); err == nil {
		logrus.Debugf("SSH key pair already exists at %s\n", directory)
		return publicKeyPath, privateKeyPath, nil
	}

	// Generate a new private key
	privateKey, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		return "", "", fmt.Errorf("failed to generate private key: %v", err)
	}

	// Encode the private key in PEM format
	privateKeyPEM := &pem.Block{
		Type:  "RSA PRIVATE KEY",
		Bytes: x509.MarshalPKCS1PrivateKey(privateKey),
	}

	// Write the private key to a file with secure permissions
	err = os.WriteFile(privateKeyPath, pem.EncodeToMemory(privateKeyPEM), 0600)
	if err != nil {
		return "", "", fmt.Errorf("failed to write private key file: %v", err)
	}

	// Generate the public key
	publicKey, err := ssh.NewPublicKey(&privateKey.PublicKey)
	if err != nil {
		return "", "", fmt.Errorf("failed to generate public key: %v", err)
	}

	// Encode the public key in the authorized_keys format
	publicKeyBytes := ssh.MarshalAuthorizedKey(publicKey)

	// Write the public key to a file with secure permissions
	err = os.WriteFile(publicKeyPath, publicKeyBytes, 0644)
	if err != nil {
		return "", "", fmt.Errorf("failed to write public key file: %v", err)
	}

	logrus.Debugf("SSH key pair generated successfully at %s\n", directory)
	return publicKeyPath, privateKeyPath, nil
}

func Base64EncodedFile(filePath string) (string, error) {
	fileBytes, err := os.ReadFile(filePath)
	if err != nil {
		return "", err
	}
	return base64.StdEncoding.EncodeToString(fileBytes), nil
}
